# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # run tests!
      # - run:
      #     name: Run tests
      #     command: |
      #       . venv/bin/activate
      #       python manage.py test

      - run: |
          pip install awscli --upgrade --user

          TAG=0.1.$CIRCLE_BUILD_NUM

          aws ecr get-login --no-include-email --region us-west-1

          docker build -t $PROJECT_NAME .

          docker tag $PROJECT_NAME:latest 753956590207.dkr.ecr.us-west-1.amazonaws.com/$PROJECT_NAME:latest

          docker push 753956590207.dkr.ecr.us-west-1.amazonaws.com/boilerplate-api:latest

      # - deploy:
      #     name: Deploy to S3 if branch is Prod
      #     command: |
      #       ./deploy.sh
      #       fi

      - store_artifacts:
          path: test-reports
          destination: test-reports
          